### PR TITLE
Back to ArduinoOnXCode4_2 folder name

### PR DESCRIPTION
**Pull request by rei-vilo**

### CODE REVIEW

**Comment by rei-vilo** [comment]
Changes:
- include user libraries from SketchBook/Libraries
- simplified sketch structure with setup() and loop() for better compatibility
- see to do for bugs and missing features

**Comment by timknapen** [comment]
Hey Olivier,

I have tried to do this pull request you've sent. But this is what I get: (attached at the bottom)
Then I get to review a lot of bullshit that I can't make sense out of (I'm using sourceTree.app)
fucking complicated... :-(

I'm sorry this all takes so long, but I just can't wrap my head around the git model yet...

best,
tim.

git fetch https://github.com/rei-vilo/Arduino-With-XCode 
From https://github.com/rei-vilo/Arduino-With-XCode
- branch            HEAD       -> FETCH_HEAD

git pull --no-commit --log https://github.com/rei-vilo/Arduino-With-XCode master 
From https://github.com/rei-vilo/Arduino-With-XCode
- branch            master     -> FETCH_HEAD
  error: refusing to lose untracked file at 'Arduino/ArduinoOnXCode4_2/ArduinoXCode4c.xcodeproj/project.xcworkspace/contents.xcworkspacedata'
  error: refusing to lose untracked file at 'Arduino/ArduinoOnXCode4_2/source/Sketch.cpp'
  error: refusing to lose untracked file at 'Arduino/ArduinoOnXCode4_2/source/main.cpp'
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/project.xcworkspace/xcuserdata/timknapen.xcuserdatad/UserInterfaceState.xcuserstate->Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/project.xcworkspace/xcuserdata/timknapen.xcuserdatad/UserInterfaceState.xcuserstate in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/Build Arduino.xcscheme->Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/Build Arduino.xcscheme in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/Upload Arduino.xcscheme->Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/Upload Arduino.xcscheme in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/xcschememanagement.plist->Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/timknapen.xcuserdatad/xcschemes/xcschememanagement.plist in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/README->Arduino/ArduinoOnXCode4/README in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/config/settings.xcconfig->Arduino/ArduinoOnXcode3/config/settings.xcconfig in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  CONFLICT (rename/delete): Rename Arduino/ArduinoOnXCode4_2/src/ArduinoProgram.h->Arduino/ArduinoOnXCode4/src/ArduinoProgram.h in HEAD and deleted in 0c6465b356280e977d7bff9c30755903a96dd330
  Auto-merging .gitignore
  CONFLICT (add/add): Merge conflict in .gitignore
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/project.pbxproj
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/project.xcworkspace/xcuserdata/tim.xcuserdatad/UserInterfaceState.xcuserstate
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes/Build and Upload.xcscheme
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes/Build.xcscheme
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes/clean.xcscheme
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes/fake target.xcscheme
  Adding Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/xcuserdata/tim.xcuserdatad/xcschemes/xcschememanagement.plist
  Auto-merging Arduino/ArduinoOnXCode4/Makefile
  CONFLICT (content): Merge conflict in Arduino/ArduinoOnXCode4/Makefile
  Auto-merging Arduino/ArduinoOnXCode4/config/Duemilanove168.xcconfig
  Auto-merging Arduino/ArduinoOnXCode4/config/Nano.xcconfig
  Auto-merging Arduino/ArduinoOnXCode4/config/Nano168.xcconfig
  Adding Arduino/ArduinoOnXCode4/config/Sanguino.xcconfig
  Adding Arduino/ArduinoOnXCode4/config/_basic_arduino_settings.xcconfig
  Adding Arduino/ArduinoOnXCode4/fake target/fake_target.1
  Adding Arduino/ArduinoOnXCode4/src/TestThing.cpp
  Auto-merging Arduino/ArduinoOnXcode3/config/BT168.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/BT328.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/Diecimila168.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/Duemilanove328.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/Mega2560.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/NG168.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/NG8.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/Pro168.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/Pro328.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/UNO.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/mega1280.xcconfig
  Auto-merging Arduino/ArduinoOnXcode3/config/mini.xcconfig
  CONFLICT (rename/rename): Rename "Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/project.xcworkspace/contents.xcworkspacedata"->"Arduino/ArduinoOnXCode4/ArduinoOnXCode4.xcodeproj/project.xcworkspace/contents.xcworkspacedata" in branch "HEAD" rename "Arduino/ArduinoOnXCode4_2/ArduinoOnXCode4.xcodeproj/project.xcworkspace/contents.xcworkspacedata"->"Arduino/ArduinoOnXCode4_2/ArduinoXCode4c.xcodeproj/project.xcworkspace/contents.xcworkspacedata" in "0c6465b356280e977d7bff9c30755903a96dd330"
  CONFLICT (rename/rename): Rename "Arduino/ArduinoOnXCode4_2/src/ArduinoProgram.cpp"->"Arduino/ArduinoOnXCode4/src/ArduinoProgram.cpp" in branch "HEAD" rename "Arduino/ArduinoOnXCode4_2/src/ArduinoProgram.cpp"->"Arduino/ArduinoOnXCode4_2/source/Sketch.cpp" in "0c6465b356280e977d7bff9c30755903a96dd330"
  CONFLICT (rename/rename): Rename "Arduino/ArduinoOnXCode4_2/src/main.cpp"->"Arduino/ArduinoOnXCode4/src/main.cpp" in branch "HEAD" rename "Arduino/ArduinoOnXCode4_2/src/main.cpp"->"Arduino/ArduinoOnXCode4_2/source/main.cpp" in "0c6465b356280e977d7bff9c30755903a96dd330"
  Automatic merge failed; fix conflicts and then commit the result.
  Completed with errors, see above

**Comment by rei-vilo** [comment]
What a mess!

Just download my branch and review it.

If it is ok, create a new branch on your repository and upload it.

Rei Vilo

**Comment by rei-vilo** [comment]
Give it up!

**Comment by timknapen** [comment]
Yes I know, it's a complete mess.

Sooo.. if I understand correctly, this is what I need to do to incorporate your changes:
- Download your version (as .zip) from this page: https://github.com/rei-vilo/Arduino-With-XCode
- add your changes to my working folder on my computer
- "commit" those changes on my local git
- "push" them to the github repo

Do you know a way to do this more automatic? So I maybe can just press a button and make your changes appear in the "master" branch of the project? 
I already found a way to create a separate "experimental" branch where I can make a mess and test new things..

best,
tim.

**Comment by rei-vilo** [comment]
Use GitHub for Mac  available at http://mac.github.com/

**Comment by timknapen** [comment]
I did use that app, but there was no way to add your pull request there either... or maybe I missed something?

**Comment by rei-vilo** [comment]
> I did use that version, but there was no way to add your pull request there either... or maybe I missed something?

No, Git for Mac doesn't manage pull requests.

Maybe GitX http://gitx.frim.nl/ ?

**Pull request closed without merging**
